### ISSUE TITLE
jsonv2.Marshal with jsonv1.DefaultOptionsV1 not equivalent to jsonv1

### ISSUE THREAD

**Issue by gazerro** [go-json-experiment/json#16]
`jsonv2.Marshal(in, jsonv1.DefaultOptionsV1())` should be semantically equivalent to `jsonv1.Marshal(in)`, but the former returns an error in the following cases

* a struct has only unexported fields
* an exported field has a non-ignored `json` tag

Also, the former clears the value when unmarshaling a JSON null into a non-nullable type.

**Comment by dsnet** [comment]
That is all expected at the moment. We haven't implemented all of the v1 compatibility layer. It will be a gradual process to get to 100% backwards compatibility.

**Comment by gazerro** [comment]
@dsnet In this case, feel free to close this issue. Thanks.

**Comment by dsnet** [comment]
Closing as we'll be addressing each v1 feature one-by-one.
