### ISSUE TITLE
NewEncoder in v2

### ISSUE THREAD

**Issue by clarkk** [go-json-experiment/json#18]
I get a compile error
`undefined: json.NewEncoder`

How to translate this into v2? :)
`if err := json.NewEncoder(gz).Encode(bytes); err != nil {`

**Comment by dsnet** [comment]
The v2 equivalent would be:
```go
if err := json.MarshalWrite(gz, bytes); err != nil { ... }
```

**Comment by dsnet** [comment]
Closing as complete.
