### ISSUE TITLE
Option for Customizing Field Omission

### ISSUE THREAD

**Issue by inoc603** [go-json-experiment/json#24]
The new `omitzero` behavior is very nice, but it can only be defined using tags. Can we introduce a new option to modify the behavior, e.g. treat `omitempty` as `omitzero`, so structs imported from another package can be marshaled with the new `omitzero` behavior？

**Comment by dsnet** [comment]
I think something like this is reasonable. Probably an option like "OmitZeroStructFields".

**Comment by dsnet** [comment]
#61 adds a caller-specified option to omit all zero struct fields.
