### ISSUE TITLE
json: cannot unmarshal JSON number into Go value of type time.Duration

### ISSUE THREAD

**Issue by crawshaw** [go-json-experiment/json#4]
I attempted to drop this package in as a replacement for `encoding/json`. It is incapable of decoding a value encoded by `encoding/json`. Is this expected?

```
package main

import (
	"log"
	"time"

	jsonexp "github.com/go-json-experiment/json"
)

func main() {
	var v struct {
		D time.Duration
	}
	src := []byte(`{"Name":"","D":155520000000000}`)
	if err := jsonexp.Unmarshal(src, &v); err != nil {
		log.Fatal(err)
	}
}
```

Produces:

```
$ go run junk.go 
2022/05/16 06:02:18 json: cannot unmarshal JSON number into Go value of type time.Duration
```

**Comment by dsnet** [comment]
Some of the notable changes between "encoding/json" and this package can be found here: https://github.com/go-json-experiment/json/blob/master/diff_test.go

**Comment by mvdan** [comment]
Is there anything else to do here? :)

**Comment by deefdragon** [comment]
Would it be possible to add a way to override how certain types are marshaled? Duration is a commonly shown example of a miss in the original encoding (and I think IP and URL both fall prey to bad encodings too off the top of my head), but I feel there will be others with time. 

Having a way to override marshaling may be benifical in the long run to both the standard library AND users who want custom marshaling of types in 3rd party libraries, but I dont know the complexity of adding that.

**Comment by mvdan** [comment]
@deefdragon you mean https://pkg.go.dev/github.com/go-json-experiment/json#Marshalers?

**Comment by dsnet** [comment]
The [jsonv1.FormatTimeDurationAsNanosecond](https://pkg.go.dev/github.com/go-json-experiment/json/v1#FormatTimeDurationAsNanosecond) call option provides a for [`jsonv2.Marshal`](https://pkg.go.dev/github.com/go-json-experiment/json#Marshal) to be configured to use the legacy behavior.
