### ISSUE TITLE
provide structured error to detect duplicate names

### ISSUE THREAD

**Issue by ajwerner** [go-json-experiment/json#41]
In some cases, the user may want to detect duplicate names when decoding and fall back to trying again with the `AllowDuplicateNames` options. The stack pointers are relatively worthless when duplicate names are enabled, but at least you can succeed. 

There is a [TODO](https://github.com/go-json-experiment/json/blob/af2d5061e6c22478c3df70f3674c70139eabe34b/jsontext/errors.go#L54-L55) to clean up the errors, but just want to track my use case specifically. 

This issue also means that I'm requesting that SyntacticError potentially have an `Unwrap` method.

**Comment by ChrisHines** [comment]
Thanks. I requested the same thing during the design process and I believe it is agreed we need it.

**Comment by dsnet** [comment]
#66 introduces `jsontext.ErrDuplicateName`, which will always be wrapped in a `jsontext.SyntacticError`, which itself has a JSON pointer to the exact error location.

The name of a duplicate JSON object member can be extracted as:
```go
err := ...
var serr jsontext.SyntacticError
if errors.As(err, &serr) && serr.Err == jsontext.ErrDuplicateName {
    ptr := serr.JSONPointer // JSON pointer to duplicate name
    name := ptr.LastToken() // duplicate name itself
    ...
}
```

**Comment by dsnet** [comment]
Closing as completed.
