### ISSUE TITLE
Custom `format` Option

### ISSUE THREAD

**Issue by lmittmann** [go-json-experiment/json#46]
How can I handle a custom `format` option in an `UnmarshalerV2`?

**Comment by dsnet** [comment]
The intention of this feature was for it to be user-customizable. However, there are some gnarly questions regarding whether the `format` option is application to exactly the current value in the tree or the entire sub-tree. This is something that we can figure out after the initial release of v2.

You can watch our discussion on the topic at https://www.youtube.com/watch?v=sgWVtViFkBs&t=2668s.

**Comment by lmittmann** [comment]
IMO the greatest `v2` feature is the possibility to overwrite the (un)marshalling logic of types one does not control. But when one type can have more than one marshaling logic I need to fall back to type proxies again, like with v1.

From my understanding of the discussion you want that the format option only applies to "leaf"-keys. Is there already an existing prototype implementation of this?

**Comment by dsnet** [comment]
Closing. The initial release of this module will not support custom formats, but we can consider it as a separate proposal within the main golang/go repo when this work lands in the stdlib.

**Comment by dsnet** [comment]
You may be interested in https://github.com/go-json-experiment/json/pull/138. We're not currently planning on adding this to the initial release of v2, but it is worth filing as a follow-up proposal.
