### ISSUE TITLE
Add option to accept mis-sized arrays

### ISSUE THREAD

**Issue by dominikh** [go-json-experiment/json#47]
Would you consider adding an option to accept JSON arrays of the wrong size when unmarshaling into a Go array?

This came up for me while decoding [Lottie](https://lottiefiles.github.io/lottie-docs/schema/), which has various arrays that _should_ contain 2 elements, as they represent 2D vectors, but the schema doesn't forbid having fewer or more than the required number of elements, and in fact many files in the wild have more than 2 elements (for reasons I do not know). I'd like to use the type system to ensure that there is always the correct number of elements, as opposed to using slices and having to use length checks everywhere.

I _could_ work around this by defining a new type and implementing a custom unmarshaler.

**Comment by dsnet** [comment]
The v1 "json" package permitted arrays with any size, while v2 "json" made the behavior strict by default.

As part of the v1 compatibility work, we'll be providing a option to have the older behavior.

**Comment by dominikh** [comment]
> That said, the current plan is only to have a global option, rather than a per-field option. Would that be acceptable for you?

That seems reasonable.

**Comment by dsnet** [comment]
https://pkg.go.dev/github.com/go-json-experiment/json/v1#UnmarshalArrayFromAnyLength now exists.

Closing as completed.
