### ISSUE TITLE
Allow `inline` tag on custom map key types that implement `encoding.Text*arshaler`

### ISSUE THREAD

**Issue by edkloczko** [go-json-experiment/json#50]
In both the standard and experimental `json` libraries, I can use a custom type that implements the [`encoding.TextUnmarshaler`](https://github.com/go-json-experiment/json/blob/ebd3a8989ca1eadb7a68e02a93448ecbbab5900c/fields.go#L151) and [`encoding.TextMarshaler`](https://github.com/go-json-experiment/json/blob/ebd3a8989ca1eadb7a68e02a93448ecbbab5900c/fields.go#L151) interfaces as map keys. When using the `inline` flag, this is [no longer allowed](https://github.com/go-json-experiment/json/blob/ebd3a8989ca1eadb7a68e02a93448ecbbab5900c/fields.go#L151).

I think I understand why the original proposal stated:

> The inlined field must be a Go struct that does not implement `Marshaler` or `Unmarshaler`

But I'm having a hard time understanding why the string-ish behavior for map keys couldn't be applied to `inline` tagged maps as well.

Thank you!

**Comment by dsnet** [comment]
I believe we could expand the restrictions, but permitting keys to support `encoding.TextMarshaler` complicates duplicate key detection. It's a solvable problem, but probably not something to solve for the first stable release of this module. The benefit of restricted features is that we can generally expand it in the future, but not the other way around.

**Comment by dsnet** [comment]
Closing this for now. The initial release of v2 will not support this, but we could investigate supporting this in the future, in which case it can go through the normal Go proposal process.
