### ISSUE TITLE
Consider to make jsontext.Decoder/Encoder as interface

### ISSUE THREAD

**Issue by morlay** [go-json-experiment/json#56]
With this changes,

we could make any json-compat configuration language (like `toml/yaml/msgpack/urlencoded`) easy to 

> define single struct once, unmarshal/marshal manies

* unmarshal from custom wrapper of  jsontext.Decoder  (`configuration language token` -> `json token` -> `go value`)
* marshal to custom wrapper of  jsontext.Encoder (`go value` -> `json token` -> `configuration language token` )

**Comment by dsnet** [comment]
Some aspects of this have been discussed previously. See https://github.com/golang/go/discussions/63397#discussioncomment-7214544

> We considered making jsontext.Encoder and jsontext.Decoder an interface, but the performance wasn't great since every method call now went through a dynamic method call, which is much slower than a concrete method call. It makes sense to optimize for the standard JSON syntax as implemented by "jsontext".

That said, nothing prevents a future where we do make this more configurable where you register a custom encoder/decoder implementation into the concrete `jsontext.Encoder` and `jsontext.Decoder` types. Such an approach would keep the standard approach fast, and the highly flexible approach slightly slower than a pure interface, which is equally slow for all situations.

Closing this here as I don't think we'll be making this change for the initial release of v2, but we're aware of the desire and flexibility benefits it could bring.

If you want to discuss this further, feel free to do so at https://github.com/golang/go/discussions/63397
